### ISSUE TITLE
Astrodon app store

### ISSUE THREAD

**Issue by elycheikhsmail** [astrodon/astrodon#19]
Astrodon desktop store 

I know astrodon still in dev and is not yet stable 

But I suggess to plan to build ecosystem around astrodon
- astrodon store (AS) :
Take as input dev code ( deno-ts + spa ) + app description and other meta 
Then build the app for target plateform (on cloud ) or take as input the build directly
save it on the cloud
and return it the zipped executable to astrodon store client on demand
- astrodon store client (ASC):
desktop app 
- allow to the final user to search for a specific app
- install astrodon desktop app by click 
under the hood ASC ask for needed permissions and install needed component 
This will be good for all :
- dev who create desktop app based astrodon : it will be easy to deliver product to there client and it will be easy for client to install here app
- astrodon author and mentainer 
Will have more conroller of app installation and get possibility to monitise this project then they can recrute some dev for full time.
- final user can get good user experience. 

In some way I aime to get have ecosystem like playStore+androidStudio+... but for desktop app multiplateform base on deno and web tech. 

This is just a suggestion.

**Comment by denyncrawford** [comment]
@elycheikhsmail Thanks for your idea, but I'm sorry to tell you this is not a priority for astrodon at the moment and probably never will, since for us it doesn't have any sense to make something like this. If you want to make an application store that shows only astrodon projects, go ahead. Probably in the future we will implement a showcase on the website but nothing more than that. I'm closing this issue, greetings.

**Comment by SOVLOOKUP** [comment]
@elycheikhsmail I'm willing to actively participate if you do

**Comment by elycheikhsmail** [comment]
> @elycheikhsmail I'm willing to actively participate if you do

Thank, I'm waiting for astrodon stable, but we can discuss about this idea in astrondon discod
